# Generated by Django 3.2.8 on 2021-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
