# Generated by Django 3.2.8 on 2021-10-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='book',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.IntegerField()),
                ('book_count', models.IntegerField()),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
        ),
    ]
