# Generated by Django 3.2.8 on 2021-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211012_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
