# Generated by Django 3.2.8 on 2021-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20211012_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstats',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookstats',
            name='book_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookstats',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
