# Generated by Django 3.2.8 on 2021-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211012_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstats',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
