# Generated by Django 3.2.8 on 2021-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='avg_book_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_book_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='fav_era',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='genres',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pages_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_books_read',
            field=models.IntegerField(null=True),
        ),
    ]
