# Generated by Django 3.2.8 on 2021-10-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
