# Generated by Django 3.2.8 on 2021-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_userstats_pages_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='avg_book_time',
            field=models.IntegerField(null=True),
        ),
    ]
