web: gunicorn bookstack.wsgi
release: python bookstack/manage.py makemigrations -noinput
release: python bookstack/manage.py collectstatic -noinput
release: python bookstack/manage.py migrate -noinput