# Generated by Django 3.2.8 on 2021-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_character',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
