# Generated by Django 3.2.8 on 2021-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_fav_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_book',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
